---
- name: Create keypair, vpc, security group, deploy ec2
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - ec2-key
    - vpc
    - sg
    - ec2-instances

- name: deploy frontend software
  hosts: frontend_hosts
  gather_facts: true
  become: true
  user: ubuntu
  roles:
    - frontend

- name: deploy db software
  hosts: db_hosts
  gather_facts: true
  become: true
  user: ubuntu
  roles:
    - database

- name: deploy backend software
  hosts: backend_hosts
  gather_facts: true
  become: true
  user: ubuntu
  roles:
    - backend

- name: display final installation information
  hosts: localhost
  connection: local
  tasks:
  - debug: msg="Installed wordpress available at http://{{ frontend_dns }} hostname"
  - debug: msg="Admin username is {{ wp_admin }} and pass is {{ wp_admin_pass }}"
  - debug: msg="Your SSH private key stored as {{ keyname }}.pem in working directory"
  - debug: msg="Written by Eldar Karazhas. Have a nice day!"
